### ISSUE TITLE
PostHog Android client still using support libraries. Need to use AndroidX

### ISSUE THREAD

**Issue by MaratTursynbek** [PostHog/posthog-android#10]
When building a project I see these warning in the logs:

"The following legacy support libraries are detected:\n:app:debugRuntimeClasspath -> com.posthog.android:posthog:1.1.2 -> com.android.support:support-annotations:28.0.0"

This behavior will not be allowed in Android Gradle plugin 8.0."

Would be nice to update dependencies client library is using.

**Comment by BattleShipPark** [comment]
This is very critical.

**Comment by marandaneto** [comment]
We're currently reworking the Android SDK and not using the support libraries anymore, will move this to WIP, so stay tuned.

**Comment by marandaneto** [comment]
Relates to https://github.com/PostHog/posthog-android/pull/27

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/releases/tag/3.0.0-alpha.4 only uses androidx, mainly `androidx.lifecycle` and nothing more, so this issue is fixed.
