### ISSUE TITLE
`identify` should not allow already identified users

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-android#108]
### Description

Relates to https://github.com/PostHog/posthog-js/pull/524

`const isKnownAnonymous = this.persistence.get_user_state() === 'anonymous'` is the check where we know if calling `identify` again is allowed or not.
If the user is already identified, calling `identify` again isn't allowed, if that's intentional, you should call `alias` instead.

If you want to identify another user again, you have to call `reset` first.
https://posthog.com/docs/product-analytics/identify#3-reset-after-logout

There are more restrictions described [here](https://posthog.com/docs/product-analytics/identify#alias-assigning-multiple-distinct-ids-to-the-same-user).

By not doing this, we might be merging users wrongly and we'll likely get a support request to split persons.

This has to be done on the other SDKs as well such as:
- [ ] iOS
- [ ] RN (js-lite)
- [X] Android

**Comment by kingabnt** [comment]
> ### Description
> Relates to [PostHog/posthog-js#524](https://github.com/PostHog/posthog-js/pull/524)
> 
> `const isKnownAnonymous = this.persistence.get_user_state() === 'anonymous'` is the check where we know if calling `identify` again is allowed or not. If the user is already identified, calling `identify` again isn't allowed, if that's intentional, you should call `alias` instead.
> 
> If you want to identify another user again, you have to call `reset` first. https://posthog.com/docs/product-analytics/identify#3-reset-after-logout
> 
> There are more restrictions described [here](https://posthog.com/docs/product-analytics/identify#alias-assigning-multiple-distinct-ids-to-the-same-user).
> 
> By not doing this, we might be merging users wrongly and we'll likely get a support request to split persons.
> 
> This has to be done on the other SDKs as well such as:
> 
> * [ ]  iOS
> * [ ]  RN (js-lite)
> * [ ]  ...
