### ISSUE TITLE
Set `is_emulator` property

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-android#113]
### Description

https://posthog.com/questions/how-to-filter-out-usage-from-i-os-android-simulators-emulators

- [ ] iOS
- [X] [Android](https://github.com/PostHog/posthog-android/pull/154)
- [ ] RN
- [ ] Flutter will get it for free once Android and RN is updated.

**Comment by marandaneto** [comment]
On Android you can do something like https://github.com/fluttercommunity/plus_plugins/blob/a71a27c5fbdbbfc56a30359a1aff0a3d3da8dc73/packages/device_info_plus/device_info_plus/android/src/main/kotlin/dev/fluttercommunity/plus/device_info/MethodCallHandlerImpl.kt#L105-L123

**Comment by thisames** [comment]
can i do that? @marandaneto

**Comment by marandaneto** [comment]
@thisames sure
