### ISSUE TITLE
Adds referrerURL automatically

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-android#138]
### Description

Context https://github.com/ueman/flutter_referrer_info/issues/2

Android already listens to `ActivityLifecycleCallbacks` so it'd be easier to add the referrerURL reading the intent Intent.EXTRA_REFERRER, Intent.EXTRA_REFERRER_NAME and or `com.android.browser.application_id`.

Prop $referrer, and $referring_domain

- [x] Android
- [ ] iOS
- [ ] RN
- [ ] Flutter

**Comment by marandaneto** [comment]
@thisames would you like to take this one?

**Comment by marandaneto** [comment]
On Android, there's also this option https://developer.android.com/google/play/installreferrer

**Comment by marandaneto** [comment]
On iOS, [this](https://developer.apple.com/help/app-store-connect/view-app-analytics/view-acquisition-sources) and [this](https://github.com/firebase/firebase-ios-sdk/blob/71d8e92d168333f79ee29a555d32fee086e66ca5/FirebaseAnalytics/Tests/SwiftUnit/AnalyticsAPITests.swift#L61-L62)
We cannot make it automatic but we can provide a method that takes a `NSUserActivity` at least.

**Comment by beradeep** [comment]
@marandaneto I'll be happy to take this one. Is it already assigned?

**Comment by marandaneto** [comment]
> @marandaneto I'll be happy to take this one. Is it already assigned?

feel free to take it.
