### ISSUE TITLE
beta session replay recording for android is not enabled to work in production?

### ISSUE THREAD

**Issue by thisames** [PostHog/posthog-android#155]
### Version

3.4.0

### Steps to Reproduce

hey guys, beta session replay recording for android is not enabled to work in production?

I'm doing several tests in several cases in the Android SDK. Getting and testing events.

I'm a little confused about the recordings. I believe I'm configuring everything correctly. However, no recordings are arriving on my posthog dashboard.

I am following all the limitations of the doc

- Session replay requires PostHog Android SDK version 3.4.0
- Requires Android API >= 26.
- Enable Recording of Session Replays for Android
- Requires Record user sessions to be enabled in the PostHog Project Settings

```java
    @Override
    public void onCreate() {
        super.onCreate();

        PostHogSessionReplayConfig replayConfig = new PostHogSessionReplayConfig();
        replayConfig.setMaskAllTextInputs(false);
        replayConfig.setMaskAllImages(false);
        replayConfig.setCaptureLogcat(true);
        replayConfig.setScreenshot(true);

        PostHogAndroidConfig config = new PostHogAndroidConfig(
                POSTHOG_API_KEY,
                POSTHOG_HOST,
                false,
                false,
                true,
                replayConfig
        );

        config.setDebug(true);
        config.setFlushAt(1);
        config.setCaptureDeepLinks(false);
        config.setCaptureApplicationLifecycleEvents(false);
        config.setCaptureScreenViews(true);
        config.setSessionReplay(true);
        config.setPreloadFeatureFlags(true);

        PostHogAndroid.setup(this, config);
    }
```
I also tried with kotlin android applications and the sdk sample itself, but I didn't get any feedback in the records.

![image](https://github.com/user-attachments/assets/7100fbf6-a1fa-43ff-8c15-2a2cfe7ec23e)

![image](https://github.com/user-attachments/assets/72016b39-6bac-42dd-a84c-6a70b36815b7)

Is the beta test closed?

### Expected Result

listing of recordings on the dashboard

### Actual Result

no recording appears.

**Comment by marandaneto** [comment]
@thisames can you try the latest version https://github.com/PostHog/posthog-android/releases/tag/3.4.2 and copy-paste the console logs?
where are you copying and pasting the code snippet? Could you let me know if you are initiating the SDK in the Application class as needed?

**Comment by thisames** [comment]
hey @marandaneto I think I found the problem. Apparently the personal access keys are not giving me authorization for anything in the SDK.

![image](https://github.com/user-attachments/assets/e084b353-1041-4356-9629-800ec9e767d1)

when I use personal keys all request return 401

![image](https://github.com/user-attachments/assets/3ec6ee01-04d2-48f6-b638-3b03741a7bad)

when I use accessKey default in  settings -> General

![image](https://github.com/user-attachments/assets/b4afaaec-bcc7-46b4-9f22-8fa81ec3bb5f)

works as should

![image](https://github.com/user-attachments/assets/b8b22248-982e-49d0-b71b-736a22576f82)

extra info:

![image](https://github.com/user-attachments/assets/6e0aaa67-133e-4baa-8fc1-b47b32b536c2)

**Comment by marandaneto** [comment]
@thisames you should not use the personal key, rather the `Project API key` found here https://us.posthog.com/project/$yourProjectId/settings/project#variables
