### ISSUE TITLE
Support `person_profiles`

### ISSUE THREAD

**Issue by marandaneto** [PostHog/posthog-android#159]
### Description

https://github.com/PostHog/product-internal/pull/637
https://github.com/PostHog/posthog-js/blob/0b40e5af5381c7d356de31fc0458e91afbfa9a6b/src/types.ts#L206-L213

`person_profiles` should be `identified_only` by default.

Options: `always`, `never`, `identified_only`.

- [ ] Android
- [ ] [iOS](https://github.com/PostHog/posthog-ios/issues/185)
- [ ] [RN](https://github.com/PostHog/posthog-js-lite/issues/240)

**Comment by thisames** [comment]
I'm finishing this for android
