### ISSUE TITLE
Posthog android should send feature flag events by default

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog-android#16]
Right now, an option controls this, which defaults to false, leading to confusion for clients, as all other client libraries have this on by default

**Comment by marandaneto** [comment]
We're currently reworking the Android SDK and the new version will be enabled by default, will move this to WIP.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/releases/tag/3.0.0-alpha.4 is enabled by default
