### ISSUE TITLE
Last event before Posthog.reset() isn't flushed and displayed on analytics front end.

### ISSUE THREAD

**Issue by AlexMisiulia** [PostHog/posthog-android#169]
### Version

3.6.0

### Steps to Reproduce

1. User has logged in into the application (`PostHog.identify()` called).
2. User has logged out of the application (`PostHog.capture("Logged out")` called).
3. User session has been reset (`PostHog.reset()` called).

### Expected Result

Identify and Logged out events are captured and displayed on analytics front end.

### Actual Result

Only identify event is captured and displayed on analytics front end.

I tried to use this code but got the same result:
```kt
PostHog.flush()
PostHog.reset()
```

This work around works for me:
```kt
       private val handler = Handler(Looper.getMainLooper())
       
       PostHog.flush()

        // work around for last event before resetPosthog isn't sent because Posthog.reset() clears
        // the internal queue of events even when flush is called
        handler.postDelayed(
            { PostHog.reset() },
            1000L
        )

```

**Comment by marandaneto** [comment]
Hello @AlexMisiulia indeed, reset should not clear the queue, indeed, let me fix it

**Comment by AlexMisiulia** [comment]
@marandaneto Hello. Thank you for the fast fix. Maybe you have ETA for a release with this fix?

**Comment by marandaneto** [comment]
its released already https://github.com/PostHog/posthog-android/releases/tag/3.6.1
