### ISSUE TITLE
personProfiles cannot be set for PostHogAndroidConfig

### ISSUE THREAD

**Issue by nvasilescu** [PostHog/posthog-android#207]
### Version

3.9.2

### Steps to Reproduce

val config = PostHogAndroidConfig(
   apiKey = POSTHOG_API_KEY,
   host = POSTHOG_HOST,
   personProfiles = PersonProfiles.IDENTIFIED_ONLY
)

this is taken from https://posthog.com/docs/libraries/android. personProfiles cannot be set on an instance of PostHogAndroidConfig

### Expected Result

personProfiles canbe set on an instance of PostHogAndroidConfig so PersonProfiles.ALWAYS can be set

### Actual Result

cannot find a parameter with this name 'personProfiles`

**Comment by marandaneto** [comment]
@nvasilescu you can simply do:

```
        val config =
            PostHogAndroidConfig(apiKey).apply {
                personProfiles = PersonProfiles.IDENTIFIED_ONLY
                ...
            }
```

I will fix the docs, thanks for spotting.
