### ISSUE TITLE
Implement Sessions

### ISSUE THREAD

**Issue by Reprevise** [PostHog/posthog-android#28]
I'd like to see [sessions](https://posthog.com/docs/data/sessions) come to the PostHog Android SDK, would be very useful for some more analytics.

**Comment by marandaneto** [comment]
We're currently reworking the Android SDK and this may change, stay tuned.

**Comment by marandaneto** [comment]
Relates to https://github.com/PostHog/posthog-android/pull/13

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/releases/tag/3.1.0-alpha.1
