### ISSUE TITLE
shouldSendFeatureFlags can make lose events

### ISSUE THREAD

**Issue by BattleShipPark** [PostHog/posthog-android#29]
In PostHog.java:479
```
if (shouldSendFeatureFlags) {
  ValueMap flags = featureFlags.getFlagVariants();
  List<String> activeFlags = featureFlags.getFlags();
```
An exception happens if PostHogFeatureFlags.reloadFeatureFlagsRequest() did not finish when featureFlags.getFlags() was called.
Although this does not make my app crash, it makes lose my very early events before reloadFeatureFlagsRequest() finishes.

**Comment by marandaneto** [comment]
We're currently reworking the Android SDK and this will be taken care of, will move this to WIP, so stay tuned.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/releases/tag/3.0.0-alpha.4 should fix this.
If the `reloadFeatureFlags` isn't finished, feature flags will just return null.
You can choose to listen for a callback once feature flags are fully reloaded. 
Check out https://github.com/PostHog/posthog-android/blob/main/USAGE.md
