### ISSUE TITLE
NullPointerException thrown on onActivityCreated

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog-android#4]
User reported we're causing some crashes with a `NullPointerException` here:

https://github.com/PostHog/posthog-android/blob/4e284e00bcd46fd1f1ac339d1f5780feb8e03e1d/posthog/src/main/java/com/posthog/android/PostHogActivityLifecycleCallbacks.java#L70

**Comment by yakkomajuri** [comment]
Just documenting for now

**Comment by mariusandra** [comment]
Fixed in 1.1.2
