### ISSUE TITLE
[Question] Expected behaviour when identifying whilst opt'd out

### ISSUE THREAD

**Issue by ouchadam** [PostHog/posthog-android#9]
Hello! 

What's the expected behaviour when calling `posthog.identify` whilst the `posthog` client is opt'd out?
I can see that the `propertiesCache` contains the properties set whilst the client was opt'd out but they're never sent.

```kotlin
posthog.optOut(true)
posthog.identify(properties)
posthog.optOut(false)
posthog.identify(id)
```

**Comment by marandaneto** [comment]
Sorry for the delay.
Yes, the properties are cached but never sent unless you opt in again.
https://posthog.com/docs/libraries/js#opt-users-out

We're currently reworking the Android SDK and this may change, stay tuned.
